# FACE AND EYES DETECTION
### Credit goes to Dr. Ryan @STEMplicity





# Overview:
## 1.) Detect a single face
## 2.) Detect multiple faces
## 3.) Detect eyes and faces

## Import

In [19]:
import numpy as np
import cv2

# 1.) Detect a single face

## Load Image

In [20]:
image_c = cv2.imread('Trudeau.jpg') # c for colored image


## Convert to gray

In [21]:
image_g = cv2.cvtColor(image_c, cv2.COLOR_BGR2GRAY)

## Show colored image

In [22]:
cv2.imshow('Trudeau in Color', image_c)
cv2.waitKey()
cv2.destroyAllWindows() 

## Show grey image

In [23]:
cv2.imshow('Trudeau in Grayscale', image_g)
cv2.waitKey()
cv2.destroyAllWindows() 

## Load the trained model CascadeClassifier for detecting face

In [24]:
# get CascadeClassifier (trained model)
face_detection = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

## Use the model on the image

CascadeClassifier.detectMultiScale(input image, Scale Factor , Min Neighbors)

- Scale Factor
    - Specifies how much reduction takes place in the image size each time during pyramiding process. 
    - For 1.2, it means image is reduced by 20% each time it’s scaled. 

- Min Neighbors
    - Parameter specifying how many neighbors each candidate rectangle should have to retain it.
    - set it to a number between 3 and 6.
    - This parameter will affect the quality of the detected faces. 
    - Higher value results in less detections but with higher quality. 

In [25]:
# The face classifier returns the region of interest in a tuple 
# Two points: upper left and bottom right coordinates
faces = face_detection.detectMultiScale(image_c, 1.1, 5) # faces = model.function(image,Scale Factor, Min Neighbors)


In [26]:
faces.shape # 1 face, 4 coordinates

(1, 4)

In [27]:
faces # 1 face detected with coordinates of the face 


array([[332, 121, 208, 208]], dtype=int32)

In [28]:
# 332, 121 are the coordinates for the top left corner /  208,208 size of the rectangle

In [29]:
faces[:,1]

array([121], dtype=int32)

In [30]:
x = faces[:, 0]
y = faces[:, 1]
w = faces[:, 2]
h = faces[:, 3]


In [31]:
x

array([332], dtype=int32)

## Draw a rectangle where the face is located

Rectangle function

Draws a simple, thick, or filled up-right rectangle.


Python: cv.Rectangle(img, pt1, pt2, color, thickness=1, lineType=8, shift=0) → None
    Parameters:	

        img – Image.
        pt1 – Vertex of the rectangle.
        pt2 – Vertex of the rectangle opposite to pt1 .
        rec – Alternative specification of the drawn rectangle.
        color – Rectangle color or brightness (grayscale image).
        thickness – Thickness of lines that make up the rectangle. Negative values, like CV_FILLED , mean that the function has to draw a filled rectangle.
        lineType – Type of the line. See the line() description.
        shift – Number of fractional bits in the point coordinates.

The function rectangle draws a rectangle outline or a filled rectangle whose two opposite corners are pt1 and pt2, or r.tl() and r.br()-Point(1,1).

In [32]:
# image, top left corner, top left corner + size of the face , color, thickness of the line
cv2.rectangle(image_c, (x,y), (x+w,y+h), (0,255,255), 3)
cv2.imshow('Single Face Detection', image_c)
cv2.waitKey(0)
    
cv2.destroyAllWindows()

# 2.) Detect multiple faces


In [33]:
#get colored and gray image
image_c = cv2.imread('Scientists.jpg')
image_g = cv2.cvtColor(image_c, cv2.COLOR_BGR2GRAY)

In [34]:
cv2.imshow('Scientists in Color', image_c)
cv2.waitKey()
cv2.destroyAllWindows() 

In [35]:
cv2.imshow('Scientists in GrayScale', image_g)
cv2.waitKey()
cv2.destroyAllWindows() 

## Load CascadeClassifier model and detect faces

In [36]:
# get CascadeClassifier (trained model)
face_detection = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
faces = face_detection.detectMultiScale(image_c, 1.1, 5)
for (x,y,w,h) in faces:
    cv2.rectangle(image_c, (x,y), (x+w,y+h), (0,255,255), 3)
    cv2.imshow('Single Face Detection', image_c)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

# 3.) Detect eyes and faces

## Load image

In [37]:
image_c = cv2.imread('Trudeau.jpg')

## Load face detection model and eye detection model (CascadeClassifier)

In [38]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

## Identify faces

In [39]:

faces = face_classifier.detectMultiScale(image_c, 1.2, 5)

for (x,y,w,h) in faces:
    cv2.rectangle(image_c,(x,y),(x+w,y+h),(0,255,255), 3)
    cv2.imshow('Trudeau Face',image_c)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    

## Use eye classifier on the face region


In [40]:
face_region = image_c[y:y+h, x:x+w]
eyes = eye_classifier.detectMultiScale(face_region)

## Print eyes

In [41]:
for (eyes_x, eyes_y, eyes_w,eyes_h) in eyes:
        cv2.rectangle(face_region,(eyes_x, eyes_y),(eyes_x + eyes_w, eyes_y + eyes_h), (0,255,0),3)
        cv2.imshow('Trudeau Face and Eyes',image_c)
        cv2.waitKey(0)
    
cv2.destroyAllWindows()

## Show only the Face Region with eyes

In [42]:
cv2.imshow('Face Region',image_c[y:y+h, x:x+w])
cv2.waitKey(0)
cv2.destroyAllWindows()   